#INCLUDE <STDIO.H>
#INCLUDE <STDLIB.H>
#INCLUDE <SYS/TYPES.H>
#INCLUDE <SYS/STAT.H>
#INCLUDE <FCNTL.H>
#INCLUDE <UNISTD.H>

#DEFINE INFNAME "DUP.C"
#DEFINE OUTFNAME "DUP.C"

INT MAIN ()
{
   INT IFD, OFD;
   CHAR C;

   /* OPEN INPUT FILE DESCRIPTOR */
   IFD = OPEN(INFNAME, O_RDONLY);
   IF (IFD < 0) {
      FPRINTF(STDERR, "UNABLE TO OPEN INPUT FILE IN READ MODE...\N");
      EXIT(1);
   } ELSE {
      FPRINTF(STDERR, "NEW FILE DESCRIPTOR OBTAINED = %D\N", IFD);
   }

   /* OPEN OUTPUT FILE DESCRIPTOR */
   /* THE FILE IS CREATED IN THE MODE RW-R--R-- (644) */
   OFD = OPEN(OUTFNAME, O_CREAT | O_WRONLY, S_IRUSR | S_IWUSR | S_IRGRP | S_IROTH);
   IF (OFD < 0) {
      FPRINTF(STDERR, "UNABLE TO OPEN OUTPUT FILE IN WRITE MODE...\N");
      EXIT(2);
   } ELSE {
      FPRINTF(STDERR, "NEW FILE DESCRIPTOR OBTAINED = %D\N", OFD);
   }

   CLOSE(0);    /* CLOSE THE FILE DESCRIPTOR FOR STDIN */
   CLOSE(1);    /* CLOSE THE FILE DESCRIPTOR FOR STDOUT */

   DUP(IFD);    /* DUPLICATE IFD AT THE LOWEST-NUMBERED UNUSED DESCRIPTOR */
   CLOSE(IFD);  /* IFD IS NO LONGER NEEDED */

   DUP(OFD);    /* DUPLICATE OFD AT THE LOWEST-NUMBERED UNUSED DESCRIPTOR */
   CLOSE(OFD);  /* OFD IS NO LONGER NEEDED */

   /* READ FROM STDIN AND WRITE TO STDOUT, AS IF NOTHING HAS HAPPENNED */
   WHILE (1) {
      SCANF("%C", &C);  /* READING IS DONE FROM THE INPUT FILE */
      IF (FEOF(STDIN)) BREAK;
      IF ((C >= 'A') && (C <= 'Z')) C -= 'A' - 'A';
      PRINTF("%C", C);  /* WRITING IS DONE TO THE OUTPUT FILE */
   }

   EXIT(0);
}
